apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test1
  annotations:
    github.com/project-slug: McAmun/verification    
spec:
  type: other
  lifecycle: unknown
  owner: pilot-team
